//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT
    {
        public int PAYMENTID { get; set; }
        public Nullable<int> ORDERID { get; set; }
        public string PAYMENTMETHOD { get; set; }
        public Nullable<decimal> PAYMENTAMOUNT { get; set; }
        public Nullable<System.DateTime> PAYMENTDATE { get; set; }
        public string PAYMENTSTATU { get; set; }
    }
}
