//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLES
    {
        public int ROLEID { get; set; }
        public string ROLENAME { get; set; }
    }
}
