//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int USERID { get; set; }
        public string USERNAME { get; set; }
        public string USERSURNAME { get; set; }
        public string USERPHONE { get; set; }
        public string USEREMAIL { get; set; }
        public string USERADDRESS { get; set; }
        public Nullable<int> USERROLEID { get; set; }
        public Nullable<bool> ISFIRSTLOGIN { get; set; }
        public string PASSWORDHASH { get; set; }
    }
}
