//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeRestaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERSVIEW
    {
        public int ORDERDETAILID { get; set; }
        public int ORDERID { get; set; }
        public Nullable<int> CUSTOMERID { get; set; }
        public string CUSTOMERNAME { get; set; }
        public string USERPHONE { get; set; }
        public Nullable<System.DateTime> ORDERDATE { get; set; }
        public Nullable<decimal> TOTALAMOUNT { get; set; }
        public Nullable<int> PRODUCTID { get; set; }
        public string PRODUCTNAME { get; set; }
        public Nullable<decimal> PRODUCTPRICE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public string ORDERTYPE { get; set; }
        public string ORDERNOTE { get; set; }
        public Nullable<int> ORDERSTATUS { get; set; }
        public string StatusCode { get; set; }
        public Nullable<int> STOCK { get; set; }
    }
}
