//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeRestaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTSTOCK
    {
        public int PRODUCT_ID { get; set; }
        public Nullable<int> STOCK { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
