//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERDETAIL
    {
        public int ORDERDETAILID { get; set; }
        public Nullable<int> ORDERID { get; set; }
        public Nullable<int> PRODUCTID { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<decimal> UNITPRICE { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public string ORDERPAID { get; set; }
        public string ORDERTYPE { get; set; }
        public string ORDERNOTE { get; set; }
        public Nullable<int> STAFFID { get; set; }
        public Nullable<int> ORDERSTATUS { get; set; }
    }
}
