//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int PRODUCTID { get; set; }
        public string PRODUCTNAME { get; set; }
        public Nullable<decimal> PRODUCTPRICE { get; set; }
        public Nullable<int> CATEGORYID { get; set; }
        public int STOCK { get; set; }
    
        public virtual PRODUCTSTOCK PRODUCTSTOCK { get; set; }
    }
}
