//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCKTRANSACTION
    {
        public int STOCKID { get; set; }
        public int PRODUCTID { get; set; }
        public int QUANTITY { get; set; }
        public System.DateTime TRANSACTIONDATE { get; set; }
        public string REASON { get; set; }
        public string PERFORMEDBY { get; set; }
    }
}
